language: node_js
node_js:
- node
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
env:
  global:
  - secure: fkVvS/INPNBwItt17YqmHMIoL5GtckyP/fTv3GtUESKfxEfAu1XwM+FhlbLYxJHmYbkyIxNU9NAsgUJ+Lk/dThqoQe2Bu4vie2Q40/vM/Xr82NVB+FiHpiWydvhN2ESHoRnOS7+B72sFluVr0Z1DN4hFaeeRefSoJzC6hHxcY9Zure/rRRLySZxh2tBLkDofib2FD71cu34R0/83iRCbG9RRvZObG/EtwUJ7uTQAGt9j9/0G3yJdS5aAjK3H8WcsBBdibdCoP05AOfuwZoKTcAzcDsnlTB/lPM2NoTOO9mnQaNgMldGy/zkwVUdKM8m5GQu9SAwd+hP6rqOh9G/4qF40HwVcqzSLJVp7c4Lfu7nwuU3eaSHfP7VDqFbV+loluCKaZA/RIh4FTlY9TlBkx3rn67JZ34UeF7CeCUbxuxWLU4+pqLtFAcxMPgc5XNgVPCdJiP7ZUoGZQ5nRQAjyb+mCzwY0BULOwSmbBPr4Hv2wDhEM7NXwcUuZtgnN3hgOtacL9mRpm1YW8OOqMrqPlmy4PgeQqdvpCvXtqZhtjdvTX+JbIIaQJlX8yWxJvG4MqUl9p0kFxuLHCf52BKYz9w9KqKfft81GJ9P7KJLLMdRrYibaE993BotLRlbIclGBA/rmKud8TBp8HhstvbV12aIYValdle9Ku3HV38C8QT4=
